### ISSUE TITLE
Create a method of converting Subtree from NLP to string or something IndexWriter can index

### ISSUE THREAD

**Issue by bkbranden** [mmako1/Stylometric-Search-Engine#4]
Need this for checking if a sentence tree structure in one document exists in any other documents

**Comment by mmako1** [comment]
- [x] Representing as string is simply calling the StanfordNLP Tree pennPrint() method

**Comment by mmako1** [comment]
- [x] Default printing and other print functions all include the english words in the POS tree so added cleaning function that removes them if wanted .
